### ISSUE TITLE
What is the state of the project?

### ISSUE THREAD

**Issue by amirouche** [ceridwen/combinators#1]
Everything is in the title :8ball:

**Comment by ceridwen** [comment]
I have been working on some other open-source projects, astroid and Macropy, mostly to improve the tooling I have available for some of the later stages of the project.  (I will need the ability to build specialized functions for grammars to optimize performance on CPython, see some discussion in 
http://lampwww.epfl.ch/~hmiller/scala2014/proceedings/p7-beguet.pdf)  The GLL parser combinators in continuation-passing style work, but can violate the performance bound of O(n^3) because I haven't optimized the data structures yet.  This is proving more difficult than I'd hoped because of the differences between different Python implementations.  Each implementation may end up requiring its own implementation.  That's what I'm hoping to finish next.

**Comment by amirouche** [comment]
thx!
